# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-27 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='', max_length=254)),
                ('advert_image', models.ImageField(upload_to='media/images')),
                ('header_image', models.ImageField(upload_to='media/images')),
                ('info', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_telephone', models.IntegerField()),
                ('slug', models.SlugField()),
                ('category', models.CharField(default='', max_length=254)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
