# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-27 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='advert_image',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='category',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='contact_telephone',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='info',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='user',
        ),
    ]
