# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20200327_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='contact_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='contact_telephone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
