# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_advert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='advert',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
