# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_auto_20200327_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='advert_image',
            field=models.ImageField(default=1, upload_to='media/images'),
            preserve_default=False,
        ),
    ]
