# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_advert_advert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='header_image',
            field=models.ImageField(default=1, upload_to='media/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advert',
            name='advert_image',
            field=models.ImageField(upload_to='media/adverts'),
        ),
    ]
