# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-30 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0008_auto_20200327_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='website',
            field=models.CharField(default='', max_length=254),
        ),
    ]
